[package]
name = "cs309-pseudofs"
version = "0.1.0"
authors = ["Jennifer Mackey <jennym1211@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
